<div class="block">
    <div class="block__element">Element Inside dsadasBlock</div>
    <div class="block__element block__element--modifier">Modifiedsadasd Element</div>
    <div class="block__element block__element--modifier">Modifieddsadas Element</div>
    <div class="block__element block__element--modifier">Modifiedsadasd Element</div>
    <div class="block__element block__element--modifier">Modifieddsadas Element</div>
    <div class="block__element block__element--modifier">Modifieddsadas Element</div>
    <div class="block__element block__element--modifier">Modifieddsadas Element</div>
    <div class="block__element block__element--modifier">Modifieddsadas Element</div>dsadas
    <div class="block__element block__element--modifier">Modifieddsadas Element</div>dsadas
    <div class="block__element block__element--modifier">Modifieddsadas Element</div>dsadas
    <div class="block__element block__element--modifier">Modifieddsadas Element</div>dsadas
    <div class="block__element block__element--modifier">Modifieddsadas Element</div>dsadas
    <div class="block__element block__element--modifier">Modified Element</div>
    <div class="block__element block__element--modifier">Modifieddsadas Element</div>dsadas
    <div class="block__element block__element--modifier">Modifieddsadas Element</div>dsadas
    <div class="block__element block__element--modifier">Modifieddsadas Element</div>dsadas